import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Landing page */}
        <Header variant="home" isLoggedIn={true} />

        {/* Home page - not logged in */}
        {/* <Header variant="home" isLoggedIn={false} /> */}

        {/* Home page - logged in */}
        {/* <Header variant="home" isLoggedIn={true} /> */}
        <main className="flex min-h-screen flex-col bg-background text-foreground">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
