import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/footer";
import { CartProvider } from "@/hooks/CartContext";
import LandingHeader from "@/components/header/landing-header";
import { AppProvider } from "@/hooks/context";
import { RootLayoutClient } from "@/components/layout/root-client-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scrollbar-hidden `}
      >
        <AppProvider>
          <CartProvider>
            {/* <main className="flex min-h-screen flex-col bg-background text-foreground ">
              <LandingHeader isLoggedIn={false} cartItemCount={10} />
              {children}
            </main> */}
            <RootLayoutClient>{children}</RootLayoutClient>
          </CartProvider>
        </AppProvider>
      </body>
    </html>
  );
}
